version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi-app:
    build:
      context: .
    container_name: fastapi_app_container
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data: